### ISSUE TITLE
Build scraper

### ISSUE THREAD

**Issue by Jakeand3rson** [Jakeand3rson/Sleeper#1]
Using BeautifulSoup, build a scraper to grab the status of users. 

url is https://codefellows.slack.com/messages/sea-python-401d2/details/

class = channel_page_all_members

**Comment by tlake** [comment]
Do you have something in mind to cover authN into Slack?

**Comment by Jakeand3rson** [comment]
Nope

**Comment by tlake** [comment]
I think that's our first step, then. I just did an experiment: grabbed the contents of our url, had BS4 prettify it, then wrote that data into an html file and opened it up in a browser. That page is Slack's login page.

**Comment by tlake** [comment]
Scrap this - we're no longer using BS4 or Selenium.
